# Generated by Django 3.0.4 on 2020-03-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_or_hostel', models.CharField(max_length=200)),
                ('room_number', models.CharField(max_length=50)),
                ('mobile_number', models.IntegerField()),
            ],
        ),
    ]
