# Generated by Django 3.0.4 on 2020-03-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_location_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='mobile_number',
            field=models.CharField(max_length=10),
        ),
    ]
